version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: entrytracker-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"  # כדי לא להפריע ל-MySQL מקומי
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: entrytracker-app
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: app_db
    ports:
      - "5000:5000"

volumes:
  db_data:
