services:
  db:
    image: mysql:8.0
    container_name: entrytracker-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: entrytracker
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306" # שיניתי ל-3307 כדי להימנע מהתנגשות עם MySQL מקומי
    volumes:
      - db_data:/var/lib/mysql

  entrytracker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: entrytracker
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: entrytracker
    ports:
      - "5000:5000"

volumes:
  db_data:
